name: rh-java

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v1
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'Build Ant starter'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-ant && ./build.sh
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build all samples using JShell'
        run: jshell build-all-samples.jsh
